# Generated by Django 4.0.3 on 2022-08-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='description',
        ),
    ]
